// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNG3qYWkMUZyYPGNspP37Y121x8zJXWaA',
    appId: '1:237586812207:web:d59c3ae67590aaa39f65da',
    messagingSenderId: '237586812207',
    projectId: 'lelo-profs',
    authDomain: 'lelo-profs.firebaseapp.com',
    storageBucket: 'lelo-profs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFe2n_i7ll5nFJF7Vm0_jp5lFQ80-E2J0',
    appId: '1:237586812207:android:cdbe6aa3509d69949f65da',
    messagingSenderId: '237586812207',
    projectId: 'lelo-profs',
    storageBucket: 'lelo-profs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmKfy-Nx3-BTnupS2AIhlCM2_-i6tNjU',
    appId: '1:237586812207:ios:82d5725e510bd46f9f65da',
    messagingSenderId: '237586812207',
    projectId: 'lelo-profs',
    storageBucket: 'lelo-profs.appspot.com',
    iosBundleId: 'com.leloprof.app001.leloprof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmKfy-Nx3-BTnupS2AIhlCM2_-i6tNjU',
    appId: '1:237586812207:ios:82d5725e510bd46f9f65da',
    messagingSenderId: '237586812207',
    projectId: 'lelo-profs',
    storageBucket: 'lelo-profs.appspot.com',
    iosBundleId: 'com.leloprof.app001.leloprof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNG3qYWkMUZyYPGNspP37Y121x8zJXWaA',
    appId: '1:237586812207:web:53d9804bf42878e79f65da',
    messagingSenderId: '237586812207',
    projectId: 'lelo-profs',
    authDomain: 'lelo-profs.firebaseapp.com',
    storageBucket: 'lelo-profs.appspot.com',
  );
}
